# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_GC\contracteditor.ui'
#
# Created: Thu Mar 30 16:39:22 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ContractEditor(object):
    def setupUi(self, ContractEditor):
        ContractEditor.setObjectName("ContractEditor")

        ContractEditor.resize(980, 970)
#        ContractEditor.setMinimumSize(QtCore.QSize(800, 750))
        self.verticalLayout = QtGui.QVBoxLayout(ContractEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.line_3 = QtGui.QFrame(ContractEditor)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label)
        self.label_3 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.n_contrat = QtGui.QLineEdit(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.n_contrat.setFont(font)
        self.n_contrat.setObjectName("n_contrat")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.n_contrat)
        self.label_4 = QtGui.QLabel(ContractEditor)
        self.label_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label__4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.date_ctr = QtGui.QDateEdit(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.date_ctr.setFont(font)
        self.date_ctr.setWrapping(False)
        self.date_ctr.setCalendarPopup(True)
        self.date_ctr.setDate(QtCore.QDate(2000, 3, 1))
        self.date_ctr.setObjectName("date_ctr")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.date_ctr)
        self.label_5 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        layout_vendeur = QtGui.QHBoxLayout()
        self.cb_nom_vendeur = QtGui.QComboBox(ContractEditor)
        self.cb_nom_vendeur.setEditable(True)
        self.cb_nom_vendeur.setObjectName("cb_nom_vendeur")
        self.b_fiche_vendeur = QtGui.QPushButton("Voir la fiche")
        self.b_fiche_vendeur.setObjectName("b_fiche_vendeur")
        layout_vendeur.addWidget(self.cb_nom_vendeur)
        layout_vendeur.addWidget(self.b_fiche_vendeur)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, layout_vendeur)
#        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cb_nom_vendeur)
        self.label_6 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        layout_acheteur = QtGui.QHBoxLayout()
        self.cb_nom_acheteur = QtGui.QComboBox(ContractEditor)
        self.cb_nom_acheteur.setEditable(True)
        self.cb_nom_acheteur.setObjectName("cb_nom_acheteur")
        self.b_fiche_acheteur = QtGui.QPushButton("Voir la fiche")
        self.b_fiche_acheteur.setObjectName("b_fiche_acheteur")
        layout_acheteur.addWidget(self.cb_nom_acheteur)
        layout_acheteur.addWidget(self.b_fiche_acheteur)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, layout_acheteur)
#        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cb_nom_acheteur)
        self.cb_marchandise = QtGui.QComboBox(ContractEditor)
        self.cb_marchandise.setEditable(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.cb_marchandise.setFont(font)
        self.cb_marchandise.setObjectName("cb_marchandise")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cb_marchandise)
        layout_quantite = QtGui.QHBoxLayout()
        self.quantite = QtGui.QLineEdit(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.quantite.setFont(font)
        self.quantite.setObjectName("quantite")
#        self.cb_unite = QtGui.QComboBox()
#        self.cb_unite.setObjectName("cb_unite")
        self.qte_total = QtGui.QLineEdit(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.qte_total.setFont(font)
        self.qte_total.setObjectName("qte_total")
        layout_quantite.addWidget(self.quantite)
#        layout_quantite.addWidget(self.cb_unite)
        layout_quantite.addWidget(QtGui.QLabel('Total (en T) : '))
        layout_quantite.addWidget(self.qte_total)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, layout_quantite)
        self.cb_logement = QtGui.QComboBox(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.cb_logement.setFont(font)
        self.cb_logement.setObjectName("cb_logement")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cb_logement)
        self.cb_adr_depart = QtGui.QComboBox(ContractEditor)
        self.cb_adr_depart.setEditable(True)
        self.cb_adr_depart.setObjectName("cb_adr_depart")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.cb_adr_depart)
        self.cb_adr_livraison = QtGui.QComboBox(ContractEditor)
        self.cb_adr_livraison.setEditable(True)
        self.cb_adr_livraison.setObjectName("cb_adr_livraison")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.cb_adr_livraison)
        layout_ville = QtGui.QHBoxLayout()
        self.cb_franco = QtGui.QCheckBox(ContractEditor)
        self.cb_franco.setObjectName("cb_franco")
#        label_ville = QtGui.QLabel("          Ville : ")
        self.cb_usine = QtGui.QComboBox()
        self.cb_usine.setObjectName("cb_usine")
        self.cb_usine.setEditable(True)
        spacerItem_ville = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        
        layout_ville.addWidget(self.cb_franco)
        layout_ville.addWidget(self.cb_usine)
        layout_ville.addSpacerItem(spacerItem_ville)
        self.formLayout.setLayout(10, QtGui.QFormLayout.FieldRole, layout_ville)
#        self.date_livraison = QtGui.QHBoxLayout()
#        self.date_livraison = QtGui.QWidget()
#        self.date_livraison.setFixedSize(QtCore.QSize(800,180))
#        self.date_livraison.setObjectName("date_livraison")
#        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.date_livraison)
        
        layout_prix = QtGui.QHBoxLayout()
        self.prix = QtGui.QLineEdit(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.prix.setFont(font)
        self.prix.setObjectName("prix")
        self.cb_monnaie = QtGui.QComboBox()
        self.cb_monnaie.setObjectName("cb_monnaie")
        label_unite = QtGui.QLabel(" le/la ")
        label_unite.setFont(font)
        self.cb_unite = QtGui.QComboBox()
        self.cb_unite.setObjectName("cb_unite")
        
        layout_prix.addWidget(self.prix)
        layout_prix.addWidget(self.cb_monnaie)
        layout_prix.addWidget(label_unite)
        layout_prix.addWidget(self.cb_unite)
        spacerItem_prix = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        layout_prix.addSpacerItem(spacerItem_prix)
#        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.prix)
        self.formLayout.setLayout(12, QtGui.QFormLayout.FieldRole, layout_prix)
        self.label_8 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_20 = QtGui.QLabel(ContractEditor)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(ContractEditor)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_12 = QtGui.QLabel(ContractEditor)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_7 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_11 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_courtage = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_courtage.setFont(font)
        self.label_courtage.setObjectName("label_courtage")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_courtage)
        self.courtage = QtGui.QLineEdit(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.courtage.setFont(font)
        self.courtage.setObjectName("courtage")
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.courtage)
        self.label_14 = QtGui.QLabel(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_14)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.cb_paiement = QtGui.QComboBox(ContractEditor)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.cb_paiement.setFont(font)
        self.cb_paiement.setObjectName("cb_paiement")
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.cb_paiement)

        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.label_notes = QtGui.QLabel()
        self.label_notes.setObjectName("label_notes")
        self.label_notes.setFont(font)
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_notes)
        
        self.t_notes = QtGui.QTextEdit()
        self.t_notes.setObjectName("t_notes")
        self.t_notes.setFont(font)
        self.t_notes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.t_notes.setMaximumHeight(100)

        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.t_notes)
        
        
#        self.horizontalLayout2 = QtGui.QHBoxLayout()
#        self.horizontalLayout2.setObjectName("horizontalLayout2")
        # RESET BUTTON
#        self.b_reset_ctr = QtGui.QPushButton(ContractEditor)
#        font = QtGui.QFont()
#        font.setFamily("Calibri")
#        font.setPointSize(9)
#        self.b_reset_ctr.setFont(font)
#        self.b_reset_ctr.setObjectName("b_reset_ctr")
#        self.horizontalLayout2.addWidget(self.b_reset_ctr)
        #CANCEL BUTTON
        self.b_cancel = QtGui.QPushButton(ContractEditor)
        self.b_cancel.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(False)
        self.b_cancel.setFont(font)
        self.b_cancel.setAutoFillBackground(False)
        self.b_cancel.setObjectName("b_cancel")
        self.horizontalLayout.addWidget(self.b_cancel)
        # VALID BUTTON
        self.b_valid = QtGui.QPushButton(ContractEditor)
        self.b_valid.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setWeight(70)
        font.setBold(True)
        self.b_valid.setFont(font)
        self.b_valid.setAutoFillBackground(False)
        self.b_valid.setObjectName("b_valid")
        self.horizontalLayout.addWidget(self.b_valid)
        
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout2 = QtGui.QVBoxLayout()
        self.verticalLayout2.addLayout(self.horizontalLayout)
#        self.verticalLayout2.addLayout(self.horizontalLayout2)
        self.horizontalLayout3 = QtGui.QHBoxLayout()
        self.horizontalLayout3.addSpacerItem(spacerItem)
        self.horizontalLayout3.addLayout(self.verticalLayout2)
        
        self.scrollArea = QtGui.QScrollArea()
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setLayout(self.formLayout)
        
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_6.addLayout(self.horizontalLayout3)
        
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        
        self.verticalLayout.addLayout(self.verticalLayout_3)
        

        self.retranslateUi(ContractEditor)
        QtCore.QMetaObject.connectSlotsByName(ContractEditor)

    def retranslateUi(self, ContractEditor):
        ContractEditor.setWindowTitle(QtGui.QApplication.translate("ContractEditor", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ContractEditor", "Nouveau contrat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ContractEditor", "Intitulés", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ContractEditor", "Détails", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ContractEditor", "Numéro de contrat : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ContractEditor", "Date du contrat : ", None, QtGui.QApplication.UnicodeUTF8))
        self.date_ctr.setDisplayFormat(QtGui.QApplication.translate("ContractEditor", "dd MMMM yyyy          -          dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ContractEditor", "Vendeur : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ContractEditor", "Acheteur : ", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_franco.setText(QtGui.QApplication.translate("ContractEditor", "Franco", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ContractEditor", "Marchandise : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ContractEditor", "Quantité : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ContractEditor", "Logement : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ContractEditor", "Adresse vendeur :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("ContractEditor", "Adresse acheteur :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ContractEditor", "Livraison :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ContractEditor", "Échéancier :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ContractEditor", "Prix : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_courtage.setText(QtGui.QApplication.translate("ContractEditor", "Courtage : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ContractEditor", "Modalités paiement : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_notes.setText(QtGui.QApplication.translate("ContractEditor", "Notes : ", None, QtGui.QApplication.UnicodeUTF8))
#        self.b_reset_ctr.setText(QtGui.QApplication.translate("ContractEditor", "Réinitialiser le contrat", None, QtGui.QApplication.UnicodeUTF8))
        self.b_valid.setText(QtGui.QApplication.translate("ContractEditor", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.b_cancel.setText(QtGui.QApplication.translate("ContractEditor", "Annuler", None, QtGui.QApplication.UnicodeUTF8))

