# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_GC\ui_contracts_manager.ui'
#
# Created: Mon Aug 07 21:18:07 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_modif_contract(object):
    def setupUi(self, modif_contract):
        modif_contract.setObjectName("modif_contract")
        modif_contract.resize(800, 600)
        self.ctr_centralwidget = QtGui.QWidget(modif_contract)
        self.ctr_centralwidget.setObjectName("ctr_centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.ctr_centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.ctr_centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_2 = QtGui.QGroupBox(self.ctr_centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cb_sort_year = QtGui.QComboBox(self.groupBox_2)
        self.cb_sort_year.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_sort_year.setObjectName("cb_sort_year")
        self.verticalLayout_10.addWidget(self.cb_sort_year)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_11)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cb_sort_client_2 = QtGui.QComboBox(self.groupBox_2)
        self.cb_sort_client_2.setMaxVisibleItems(20)
        self.cb_sort_client_2.setObjectName("cb_sort_client_2")
        self.horizontalLayout_6.addWidget(self.cb_sort_client_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.cb_sort_fourniss = QtGui.QComboBox(self.groupBox_2)
        self.cb_sort_fourniss.setMaxVisibleItems(20)
        self.cb_sort_fourniss.setObjectName("cb_sort_fourniss")
        self.horizontalLayout_7.addWidget(self.cb_sort_fourniss)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.cb_marchandise = QtGui.QComboBox(self.groupBox_2)
        self.cb_marchandise.setObjectName("cb_marchandise")
        self.horizontalLayout_3.addWidget(self.cb_marchandise)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.ctr_centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.b_rechercher = QtGui.QPushButton(self.groupBox)
        self.b_rechercher.setObjectName("b_rechercher")
        self.gridLayout.addWidget(self.b_rechercher, 3, 2, 1, 1)
        self.rb_r_n_ctr = QtGui.QRadioButton(self.groupBox)
        self.rb_r_n_ctr.setText("")
        self.rb_r_n_ctr.setObjectName("rb_r_n_ctr")
        self.gridLayout.addWidget(self.rb_r_n_ctr, 0, 0, 1, 1)
        self.l_n_ctr = QtGui.QLineEdit(self.groupBox)
        self.l_n_ctr.setObjectName("l_n_ctr")
        self.gridLayout.addWidget(self.l_n_ctr, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.l_n_client = QtGui.QLineEdit(self.groupBox)
        self.l_n_client.setObjectName("l_n_client")
        self.gridLayout.addWidget(self.l_n_client, 1, 2, 1, 1)
        self.rb_r_n_client = QtGui.QRadioButton(self.groupBox)
        self.rb_r_n_client.setText("")
        self.rb_r_n_client.setObjectName("rb_r_n_client")
        self.gridLayout.addWidget(self.rb_r_n_client, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.l_n_fourniss = QtGui.QLineEdit(self.groupBox)
        self.l_n_fourniss.setObjectName("l_n_fourniss")
        self.gridLayout.addWidget(self.l_n_fourniss, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.rb_r_n_fourniss = QtGui.QRadioButton(self.groupBox)
        self.rb_r_n_fourniss.setText("")
        self.rb_r_n_fourniss.setObjectName("rb_r_n_fourniss")
        self.gridLayout.addWidget(self.rb_r_n_fourniss, 2, 0, 1, 1)
        self.b_reinit_list = QtGui.QPushButton(self.groupBox)
        self.b_reinit_list.setObjectName("b_reinit_list")
        self.gridLayout.addWidget(self.b_reinit_list, 3, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.ctr_centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.b_new_contract = QtGui.QPushButton(self.groupBox_3)
        self.b_new_contract.setMinimumSize(QtCore.QSize(130, 0))
        self.b_new_contract.setObjectName("b_new_contract")
        self.verticalLayout_2.addWidget(self.b_new_contract)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.t_ctr_list = QtGui.QTreeWidget(self.ctr_centralwidget)
        self.t_ctr_list.setStyleSheet("")
        self.t_ctr_list.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.t_ctr_list.setProperty("showDropIndicator", False)
        self.t_ctr_list.setItemsExpandable(True)
        self.t_ctr_list.setObjectName("t_ctr_list")
        self.t_ctr_list.headerItem().setText(0, "1")
        self.t_ctr_list.header().setSortIndicatorShown(True)
        self.horizontalLayout.addWidget(self.t_ctr_list)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.t_ctr_total = QtGui.QTreeWidget(self.ctr_centralwidget)
        self.t_ctr_total.setEnabled(False)
        self.t_ctr_total.setObjectName("t_ctr_total")
        self.t_ctr_total.headerItem().setText(0, "1")
        self.t_ctr_total.header().setVisible(True)
        self.t_ctr_total.header().setStretchLastSection(False)
        self.horizontalLayout_8.addWidget(self.t_ctr_total)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        modif_contract.setCentralWidget(self.ctr_centralwidget)

        self.retranslateUi(modif_contract)
        QtCore.QMetaObject.connectSlotsByName(modif_contract)

    def retranslateUi(self, modif_contract):
        modif_contract.setWindowTitle(QtGui.QApplication.translate("modif_contract", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("modif_contract", "Gestionnaire de contrats", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("modif_contract", "Afficher les contrats selon :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("modif_contract", "Année", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("modif_contract", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("modif_contract", "Client :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("modif_contract", "Fournisseur :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("modif_contract", "Marchandise :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("modif_contract", "Recherche un contrat par :", None, QtGui.QApplication.UnicodeUTF8))
        self.b_rechercher.setText(QtGui.QApplication.translate("modif_contract", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("modif_contract", "numéro contrat client :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("modif_contract", "numéro contrat G&Cie :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("modif_contract", "numéro contrat fournisseur :", None, QtGui.QApplication.UnicodeUTF8))
        self.b_reinit_list.setText(QtGui.QApplication.translate("modif_contract", "Réinitialiser la liste", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("modif_contract", "Créer un contrat :", None, QtGui.QApplication.UnicodeUTF8))
        self.b_new_contract.setText(QtGui.QApplication.translate("modif_contract", "Nouveau contrat", None, QtGui.QApplication.UnicodeUTF8))

